#!/bin/sh
# postrm script for mechatrax-dkms-sys-mods
#
# see: dh_installdeb(1)

set -e

CONFIG=/boot/firmware/config.txt

case "$1" in
    purge|remove|upgrade|abort-install|disappear)
        if [ -e $CONFIG ]; then
            raspi-config nonint clear_config_var arm_64bit $CONFIG
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
