#!/bin/sh
# postinst script for mechatrax-dkms-sys-mods
#
# see: dh_installdeb(1)

set -e

CONFIG=/boot/firmware/config.txt

case "$1" in
    configure)
        if [ -e $CONFIG ]; then
            raspi-config nonint set_config_var arm_64bit 0 $CONFIG
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
